create procedure SP_CLIENTES
@OP TINYINT= 0,
@CL_ID TINYINT = 0,
@CL_NOMBRE VARCHAR(200)= NULL,
@CL_RFC CHAR(13)= NULL,
@CL_CORREO CHAR(200)= NULL,
@CL_LADA CHAR(3) = NULL,
@CL_TELEFONO CHAR(7) = NULL,
@CL_CALLE VARCHAR(150)= NULL,
@CL_NUMERO_EXT CHAR(10) = NULL,
@CL_CTABANCARIA VARCHAR(150) = NULL,
@CL_CONTACTO VARCHAR (150) = NULL,
@CL_TELEF_CONTACTO CHAR(10) = NULL,
@CL_REGIMEN CHAR (3) = NULL
AS

	BEGIN
	--GUARDA Y ACTUALIZA
		IF @OP = 1
		BEGIN
			SET @CL_ID=(SELECT ISNULL(MAX(CL_ID),0) + 1 FROM CLIENTES)
			IF NOT EXISTS(SELECT * FROM CLIENTES WHERE CL_ID = @CL_ID)
				BEGIN 
					INSERT INTO CLIENTES (CL_ID, CL_NOMBRE, CL_RFC, CL_CORREO, CL_LADA, CL_TELEFONO, CL_CALLE, CL_NUMERO_EXT, CL_CTABANCARIA, CL_CONTACTO, CL_TELEF_CONTACTO, CL_REGIMEN)
					VALUES (@CL_ID, @CL_NOMBRE, @CL_RFC,@CL_CORREO, @CL_LADA, @CL_TELEFONO, @CL_CALLE, @CL_NUMERO_EXT, @CL_CTABANCARIA, @CL_CONTACTO, @CL_TELEF_CONTACTO, @CL_REGIMEN)
				END
		END 
		--ACTUALIZAR DATOS
		
	--------------------------------------------------------------------------------------------------------------------------------------------------------
		IF @OP = 2
		BEGIN 
			--ELIMINA DATOS EN ESPECIFICO
			DELETE FROM CLIENTES WHERE CL_ID = @CL_ID
		END
END

		
		IF @OP = 3
		
			BEGIN 
				UPDATE CLIENTES SET CL_NOMBRE = @CL_NOMBRE, CL_RFC = @CL_RFC, CL_CORREO = @CL_CORREO, CL_LADA = @CL_LADA, CL_TELEFONO = @CL_TELEFONO, 
				CL_CALLE = @CL_CALLE, CL_NUMERO_EXT = @CL_NUMERO_EXT, CL_CTABANCARIA = @CL_CTABANCARIA, CL_CONTACTO = @CL_CONTACTO, CL_TELEF_CONTACTO = @CL_TELEF_CONTACTO, CL_REGIMEN = @CL_REGIMEN
				WHERE CL_ID = @CL_ID
			END


/*	IF @OP = 3
	BEGIN
			SELECT PE_FOLIO, C.CL_NOMBRE,P.PE_FECHA,dbo.FN_IMP_PEDIDOS(PE_FOLIO) as importe
			FROM PEDIDOS P 
			INNER JOIN CLIENTES C ON P.PE_ID_CLIENTE = CL_ID
	END*/





