Alter PROCEDURE SP_PRODUCTOS 
@OP TINYINT = 0,
@PR_ID TINYINT = 0,
@PR_NOMBRE VARCHAR (200) = NULL,
@PR_ID_UNIDAD TINYINT = 0,
@PR_STOCK_MIN FLOAT =0,
@PR_STOCK_MAX FLOAT =0,
@PR_ID_TP TINYINT =0,
@PR_PRECIO FLOAT =0,
@PR_IVA FLOAT =0

AS 
BEGIN
	--GUARDA Y ACTUALIZA
		IF @OP = 1
		BEGIN
			SET @PR_ID=(SELECT ISNULL(MAX(PR_ID),0) + 1 FROM PRODUCTOS)
			IF NOT EXISTS(SELECT * FROM PRODUCTOS WHERE PR_ID = @PR_ID)
				BEGIN 
					INSERT INTO PRODUCTOS(PR_ID, PR_NOMBRE, PR_ID_UNIDAD, PR_STOCK_MIN, PR_STOCK_MAX, PR_ID_TP, PR_PRECIO, PR_IVA)
					VALUES (@PR_ID, @PR_NOMBRE, @PR_ID_UNIDAD, @PR_STOCK_MIN, @PR_STOCK_MAX, @PR_ID_TP, @PR_PRECIO, @PR_IVA)
				END
		END 
		--ACTUALIZAR DATOS
		
	--------------------------------------------------------------------------------------------------------------------------------------------------------
		IF @OP = 2
		BEGIN 
			--ELIMINA DATOS EN ESPECIFICO
			DELETE FROM PRODUCTOS WHERE PR_ID = @PR_ID
		END

		if @OP = 3
			BEGIN 
				UPDATE PRODUCTOS SET PR_NOMBRE = @PR_NOMBRE, PR_ID_UNIDAD = @PR_ID_UNIDAD, PR_STOCK_MIN = @PR_STOCK_MIN, PR_STOCK_MAX = @PR_STOCK_MAX,
				PR_ID_TP= @PR_ID_TP, PR_PRECIO = @PR_PRECIO, PR_IVA = @PR_IVA 
				WHERE PR_ID = @PR_ID
			END
END