CREATE PROCEDURE SP_INSERT_PRODUCTOS 
@PR_ID TINYINT = 0,
@PR_NOMBRE VARCHAR (200) = NULL,
@PR_ID_UNIDAD TINYINT = 0,
@PR_STOCK_MIN FLOAT =0,
@PR_STOCK_MAX FLOAT =0,
@PR_ID_TP TINYINT =0,
@PR_PRECIO FLOAT =0,
@PR_IVA FLOAT =0

AS 
	BEGIN 
		 INSERT INTO PRODUCTOS(PR_ID, PR_NOMBRE, PR_ID_UNIDAD, PR_STOCK_MIN, PR_STOCK_MAX, PR_ID_TP, PR_PRECIO, PR_IVA)
		VALUES (@PR_ID, @PR_NOMBRE, @PR_ID_UNIDAD, @PR_STOCK_MIN, @PR_STOCK_MAX, @PR_ID_TP, @PR_PRECIO, @PR_IVA)
	END
	
	
	
CREATE PROCEDURE SP_BUSCAR_PRODUCTOS
AS
BEGIN
	SELECT * FROM PRODUCTOS
END

exec SP_BUSCAR_PRODUCTOS

